version: "3"

services:
  reconcile-publish:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${APP_PORT_EXPOSED}:${APP_PORT}
    volumes:
      - .env:/app/.env
      - uploads:/app/uploads
    networks:
      - reconcile-backend

volumes:
  uploads:
    driver: local

networks:
  reconcile-backend:
    name: reconcile-backend
    external: true
